[book]
title = "Easy Node Validator Toolbox Manual"
author = "Easy Node"
description = "Easy Node's User Manual for validatortoolbox Harmony ONE Validator Installer & Management Application"
language = "en"
multilingual = false
create-missing = false
build-dir="docs"

[output.html]
theme = "ayu"
default-theme = "rust"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/easy-node-one/mdbook_validatortoolbox"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/easy-node-one/mdbook_validatortoolbox/edit/main/{path}"
cname = "validator-toolbox-guide.easynode.one"
no-section-label = true

[output.html.playground]
editable = true
line-numbers = true